# Generated by Django 5.1.2 on 2024-10-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservice',
            name='dtype',
            field=models.CharField(choices=[('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('plumbing', 'Plumbing')], default='Electrical', max_length=50),
            preserve_default=False,
        ),
    ]
