# Generated by Django 5.1.2 on 2024-10-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.IntegerField(default=5),
        ),
    ]
